### ISSUE TITLE
mixtapes won't render running on ubunutu 16.04

### ISSUE THREAD

**Issue by leachy14** [NoonPacific/White-Label-Web-Template#3]
Running locally works but when trying to load on ubuntu 16.04 it will not render the mixtapes

**Comment by leachy14** [comment]
This error gets thrown in conolse:
`main.js:1 Uncaught Error: Sprockets::FileNotFound: couldn't find file 'SoundManager2/script/soundmanager2.js'
  (in /root/wl/source/js/main.js:3)`

**Comment by leachy14** [comment]
Fixed by editing main.js and changing SoundManger2 to soundmanger2

**Comment by coffee-cup** [comment]
Interesting, tried changing to `soundmanager2` on mac and got a similar error. Will look into this further, thanks.

**Comment by coffee-cup** [comment]
Fixed with your suggestion. Re-cloned to fix name error after re-naming in `main.js`. Name is most likely being cached. 👍
